### ISSUE TITLE
Allow vcase user to use GetOffer/GetOffers endpoints

### ISSUE THREAD

**Issue by waylaidwanderer** [OPSkins/trade-opskins-api#56] opened 2018-07-19 21:14 UTC

**Comment by SzymonLisowiec** [comment] 2018-07-19 22:07
Duplicate of #39

**Comment by waylaidwanderer** [comment] 2018-07-19 22:55
Not really, it's a different request. A Trade Offer object has different data compared to `ICaseSite/GetTradeStatus`.

**Comment by jor112358** [comment] 2019-01-01 14:49
Yes, I need this too, so I can get the case opening history.

**Closed** 2022-09-06 17:20 UTC
Labels: enhancement, ticket created
