### ISSUE TITLE
Offers report Invalid state on acceptance.

### ISSUE THREAD

**Issue by tacyarg** [OPSkins/trade-opskins-api#79] opened 2018-08-17 17:28 UTC
Offers report as Invalid state on acceptance.

When checking offer state, offers somtimes report as "Invalid Items" (state 8) for a period of time before transitioning to accepted.

**Comment by ha1331** [comment] 2018-08-17 18:43
I think this might be a duplicate or a bug in rebound

**Comment by ha1331** [comment] 2018-08-17 18:45
duplicate of a closed issue: #59

**Comment by ha1331** [comment] 2018-08-17 18:46
@tacyarg do you get this for case opening trades or trades in general?

**Comment by tacyarg** [comment] 2018-08-18 02:58
Case openings, I am not sure if an existence of the bug appears with peer to peer exchanges.

**Comment by SmileFX** [comment] 2018-08-20 19:31
Had the exact bug yesterday a few times aswell, might be a problem of the API thinking the key isnt in the Inventory of the user...

**Comment by ha1331** [comment] 2018-08-20 21:32
@tacyarg what do you mean by "item properly populated"? You mean after it goes from state 8 or 9 (don't remember which it goes to after the use accepts but prior to opskins doing their thing to "open the case") to being accepted? What I'm asking is, do you have trades that are state accepted, but doesn't have the items the user received?

**Comment by tacyarg** [comment] 2018-08-21 01:45
yes.

**Comment by tacyarg** [comment] 2018-08-21 01:51
what

**Comment by QuantumLlama** [comment] 2018-09-04 22:07
Hello,

We pushed an update few minutes ago to help resolve issues with offers going from a permanent state (e.g. invalid) to another permanent state (e.g. accepted). We would appreciate any further feedback regarding this.

We are still investigating the issue regarding the empty `items` array on some API outputs. Although we are able to reproduce, more details regarding this would be appreciated.

Thank you

**Closed** 2018-09-18 20:09 UTC
Labels: bug
